failed lint

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -19,3 +19,6 @@ jobs:
         run: docker-compose run --rm app sh -c "python manage.py test" # run the test command
       - name: Lint # name of the step (can be anything)
         run: docker-compose run --rm app sh -c "flake8" # run the lint command 
+      - name: Exit if test or lint fails # prevent the push if failure
+        run: exit 1
+        if: ${{ failure() }}
